In [ ]:
# Source https://www.reddit.com/r/datasets/comments/2awdgx/i_made_this_dataset_of_all_of_igns_game_reviews/

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('./gamedata_good.csv')
df.sample(15)

,Game,Platform,Score,Genre
5014,Star Defense,iPhone,9.0,Strategy
9426,Flushed Away,GameCube,4.0,Action
4001,The Simpsons Arcade,iPhone,7.0,Action
3173,Arc Rise Fantasia,Wii,6.5,RPG
10302,Leisure Suit Larry: Magna Cum Laude,Wireless,3.0,Adventure
8385,Picross DS,Nintendo DS,9.0,Puzzle
6130,SCORE International Baja 1000,Wii,5.0,Racing
1133,Mass Effect 3: Leviathan,PlayStation 3,7.5,RPG
916,The Walking Dead: The Game -- Episode 5: No Ti...,PC,9.5,Adventure
13650,Tiger Woods PGA Tour 2003,GameCube,8.9,Sports
16463,Man of War II: Chains of Command,PC,5.7,Strategy
11258,Silent Hunter III,PC,8.8,Simulation
6054,Virtua Racing Deluxe,Sega 32X,7.5,Racing
9144,National Lampoon's Greek Games,Wireless,3.0,Party
11230,Tom Clancy's Splinter Cell Chaos Theory,PC,9.6,"Action, Adventure"

In [4]:
df['Genre'] = df['Genre'].str.split(',').str[0]
df.head()

                         Game       Platform  Score    Genre
0  Wolfenstein: The New Order       Xbox One    7.8  Shooter
1                Mario Kart 8          Wii U    9.0   Racing
2               Sportsfriends  PlayStation 3    8.7   Action
3               Sportsfriends  PlayStation 4    8.7   Action
4               Sportsfriends             PC    8.7   Action

In [5]:
df['Genre'].value_counts()

Action          4765
Sports          2108
Shooter         1494
Racing          1423
Strategy        1084
Adventure       1026
Puzzle          1005
RPG              878
Platformer       781
Fighting         620
Simulation       544
Music            406
Flight           182
Card             166
Party            138
Wrestling        129
Trivia           117
Hunting          114
Board            107
Virtual Pet       80
Pinball           78
Educational       69
Compilation       57
Productivity      40
None              38
Casino            31
Battle            30
Other             21
Adult              2
Baseball           1
Name: Genre, dtype: int64

In [6]:
other = ('Pinball', 'Educational', 'Compilation', 'Productivity', 'None',
        'Casino', 'Battle', 'Adult')
#Baseball           

df['Genre'] = df['Genre'].replace(['Pinball', 'Educational', 'Compilation', 'Productivity', 'None', 
                                   'Casino', 'Battle', 'Adult', 'Virtual Pet', 'Baseball'],
                                  ['Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other',
                                   'Other', 'Other', 'Sports'])
                
df['Genre'].value_counts()

Action        4765
Sports        2109
Shooter       1494
Racing        1423
Strategy      1084
Adventure     1026
Puzzle        1005
RPG            878
Platformer     781
Fighting       620
Simulation     544
Other          446
Music          406
Flight         182
Card           166
Party          138
Wrestling      129
Trivia         117
Hunting        114
Board          107
Name: Genre, dtype: int64

In [12]:
def recommend(console, genre):
    system = df[df['Platform'] == console]
    games = system[system['Genre'] == genre]
    return games.sample(1)

In [17]:
recommend('Xbox One', 'Shooter')

               Game  Platform  Score    Genre
5  Super TIME Force  Xbox One    7.5  Shooter